---
version: "3.8"
services:
  enrichstream-test:
    build:
      context: ComponentTest
      secrets:
        - GITHUB_TOKEN
        - GITHUB_ACTOR
    environment:
      KAFKA__URL: kafka:19092
      KAFKA__OAUTH2__CLIENTID: default-access
      KAFKA__OAUTH2__CLIENTSECRET: default-access-secret
      KAFKA__OAUTH2__SCOPE: kafka
      KAFKA__OAUTH2__TOKENENDPOINT: http://keycloak:1852/realms/local-development/protocol/openid-connect/token
    depends_on:
      enrichstream-jobmanager:
        condition: service_healthy

  enrichstream-jobmanager:
    build:
      secrets:
        - GITHUB_TOKEN
        - GITHUB_ACTOR
    command: |
      standalone-job
      --job-classname cheetah.example.enrichstream.job.EnrichStreamJob
      --kafka-bootstrap-servers kafka:19092
      --kafka-group-id EnrichStream-group-id
      --kafka-security-protocol SASL_PLAINTEXT
      --input-kafka-topic-enriching EnrichStreamEnrichTopic
      --input-kafka-topic-main-source EnrichStreamInputTopic
      --output-kafka-topic-main-sink EnrichStreamOutputTopic
    environment:
      KAFKA_CLIENT_ID: default-access
      KAFKA_CLIENT_SECRET: default-access-secret
      KAFKA_SCOPE: kafka
      KAFKA_TOKEN_URL: http://keycloak:1852/realms/local-development/protocol/openid-connect/token
      FLINK_PROPERTIES: |
        jobmanager.rpc.address: enrichstream-jobmanager
        scheduler-mode: reactive
        rest.flamegraph.enabled: true
        state.backend: rocksdb
        state.checkpoints.dir: file:///checkpoints/processing
        state.savepoints.dir: file:///checkpoints/processing
        execution.checkpointing.interval: 300 seconds
        execution.checkpointing.min-pause: 240 seconds
    depends_on:
      - enrichstream-taskmanager
    volumes:
      - flink:/checkpoints
    healthcheck:
      test: curl localhost:8081/jobs | grep -q '"status":"RUNNING"' || exit -1
      interval: 1s
      timeout: 1s
      retries: 30

  enrichstream-taskmanager:
    build:
      secrets:
        - GITHUB_TOKEN
        - GITHUB_ACTOR
    command: taskmanager
    environment:
      FLINK_PROPERTIES: |
        jobmanager.rpc.address: enrichstream-jobmanager
        taskmanager.memory.process.size: 4gb
        taskmanager.numberOfTaskSlots: 2
    volumes:
      - flink:/checkpoints

volumes:
  flink:

secrets:
  GITHUB_TOKEN:
    environment: GITHUB_TOKEN
  GITHUB_ACTOR:
    environment: GITHUB_ACTOR

networks:
  default:
    name: "cheetah-infrastructure"
    external: true
