version: "3"
services:
  multiplesideoutputexample-test:
    build:
      context: ComponentTest
      dockerfile: Dockerfile
      secrets:
        - GITHUB_TOKEN
        - GITHUB_ACTOR
    environment:
      KAFKA__URL: kafka:19092
      KAFKA__CLIENTID: ClientId
      KAFKA__CLIENTSECRET: 1234
      KAFKA__AUTHENDPOINT: http://cheetahoauthsimulator/oauth2/token

  multiplesideoutputexample-job:
    image: ${DOCKER_REGISTRY-}multiplesideoutputexample-job
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - MAVEN_ARGS=${EXTRA_MAVEN_ARGS-}
      secrets:
        - GITHUB_TOKEN
        - GITHUB_ACTOR
    command: |
      standalone-job
      --job-classname sideOutputExample.job.MultipleSideOutputExampleJob
      --input-kafka-bootstrap-servers kafka:19092
      --input-kafka-topic MultipleSideOutputExampleInputTopic
      --output-kafka-topic MultipleSideOutputExampleOutputTopic
      --output-kafka-bootstrap-servers kafka:19092
    environment:
      KAFKA_CLIENT_ID: ClientId
      KAFKA_CLIENT_SECRET: 1234
      KAFKA_TOKEN_URL: http://cheetahoauthsimulator/oauth2/token
      FLINK_PROPERTIES: |
        jobmanager.rpc.address: multiplesideoutputexample-job
        scheduler-mode: reactive
        rest.flamegraph.enabled: true
        state.backend: rocksdb
        state.checkpoints.dir: file:///checkpoints/processing
        state.savepoints.dir: file:///checkpoints/processing
        execution.checkpointing.interval: 300 seconds
        execution.checkpointing.min-pause: 240 seconds
    depends_on:
      - multiplesideoutputexample-job-taskmanager
    volumes:
      - flink:/checkpoints
    healthcheck:
      test: curl localhost:8081/jobs | grep -q '"status":"RUNNING"' || exit -1
      interval: 1s
      timeout: 1s
      retries: 30

  multiplesideoutputexample-job-taskmanager:
    image: ${DOCKER_REGISTRY-}multiplesideoutputexample-job
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - MAVEN_ARGS=${EXTRA_MAVEN_ARGS-}
      secrets:
        - GITHUB_TOKEN
        - GITHUB_ACTOR
    command: taskmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: multiplesideoutputexample-job
        taskmanager.memory.process.size: 4gb
        taskmanager.numberOfTaskSlots: 2
    volumes:
      - flink:/checkpoints

volumes:
  flink:

secrets:
  GITHUB_TOKEN:
    environment: GITHUB_TOKEN
  GITHUB_ACTOR:
    environment: GITHUB_ACTOR

networks:
  default:
    name: "cheetah-infrastructure"
    external: true
