---
version: "3.8"
services:
  externallookup-test:
    build:
      context: ComponentTest
      secrets:
        - GITHUB_TOKEN
        - GITHUB_ACTOR
    environment:
      KAFKA__URL: kafka:19092
      KAFKA__OAUTH2__CLIENTID: default-access
      KAFKA__OAUTH2__CLIENTSECRET: default-access-secret
      KAFKA__OAUTH2__SCOPE: kafka
      KAFKA__OAUTH2__TOKENENDPOINT: http://keycloak:1852/realms/local-development/protocol/openid-connect/token
    depends_on:
      externallookup-job:
        condition: service_healthy

  externallookup-job:
    build:
      secrets:
        - GITHUB_TOKEN
        - GITHUB_ACTOR
    command: |
      standalone-job
      --job-classname cheetah.example.externallookup.job.ExternalLookupJob
      --kafka-bootstrap-servers kafka:19092
      --kafka-group-id ExternalLookup-group-id
      --kafka-security-protocol SASL_PLAINTEXT
      --input-kafka-topic-main-source ExternalLookupInputTopic
      --output-kafka-topic-main-sink ExternalLookupOutputTopic
    environment:
      KAFKA_CLIENT_ID: default-access
      KAFKA_CLIENT_SECRET: default-access-secret
      KAFKA_SCOPE: kafka
      KAFKA_TOKEN_URL: http://keycloak:1852/realms/local-development/protocol/openid-connect/token
      ID_SERVICE_URL: http://id-service:8080/
      ID_SERVICE_TOKEN_URL: http://keycloak:1852/realms/local-development/protocol/openid-connect/token
      ID_SERVICE_CLIENT_ID: default-access
      ID_SERVICE_CLIENT_SECRET: default-access-secret
      ID_SERVICE_SCOPE: openid
      ID_SERVICE_OPTIONAL: optionalParam
      FLINK_PROPERTIES: |
        jobmanager.rpc.address: externallookup-job
        scheduler-mode: reactive
        rest.flamegraph.enabled: true
        state.backend: rocksdb
        state.checkpoints.dir: file:///checkpoints/processing
        state.savepoints.dir: file:///checkpoints/processing
        execution.checkpointing.interval: 300 seconds
        execution.checkpointing.min-pause: 240 seconds
    depends_on:
      - externallookup-job-taskmanager
    volumes:
      - flink:/checkpoints
    healthcheck:
      test: curl localhost:8081/jobs | grep -q '"status":"RUNNING"' || exit -1
      interval: 1s
      timeout: 1s
      retries: 30

  externallookup-job-taskmanager:
    build:
      secrets:
        - GITHUB_TOKEN
        - GITHUB_ACTOR
    command: taskmanager
    environment:
      FLINK_PROPERTIES: |
        jobmanager.rpc.address: externallookup-job
        taskmanager.memory.process.size: 4gb
        taskmanager.numberOfTaskSlots: 2
    volumes:
      - flink:/checkpoints

  id-service:
    tty: true
    hostname: id-service
    build:
      context: ExternalLookupApi
      dockerfile: Dockerfile
      secrets:
        - GITHUB_ACTOR
        - GITHUB_TOKEN
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 1862:8080

volumes:
  flink:

secrets:
  GITHUB_TOKEN:
    environment: GITHUB_TOKEN
  GITHUB_ACTOR:
    environment: GITHUB_ACTOR

networks:
  default:
    name: "cheetah-infrastructure"
    external: true
