name: "Run Component test"
description: "Build image and run component test"

inputs:
  context-path:
    description: Path to Dockerfile
    required: true
  access-token:
    description: Personal access token to access external dependencies 
    required: true
  initial-kafka-topics:
    description: Initial topics to create in kafka
    required: false
    
runs:
  using: composite
  steps:
    - name: Log in to the Container registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ inputs.access-token }}

    - name: Checkout trifork/cheetah-development-infrastructure
      uses: actions/checkout@v4
      with:
        repository: trifork/cheetah-development-infrastructure
        token: ${{ inputs.access-token }}
        path: development-infrastructure

    - name: "Build images"
      working-directory: ${{ inputs.context-path }}
      shell: bash
      run: docker compose build --quiet
      env:
        GITHUB_ACTOR: ${{ github.actor }}
        GITHUB_TOKEN: ${{ inputs.access-token }}

    - name: "Start development infrastructure"
      working-directory: development-infrastructure/
      shell: bash
      run: docker compose --profile kafka --profile oauth --profile opensearch up -d --build --quiet-pull
      env:
        INITIAL_KAFKA_TOPICS: ${{ inputs.initial-kafka-topics }}
        DOCKER_REGISTRY: ghcr.io/trifork/

    - name: "Run Component Test"
      working-directory: ${{ inputs.context-path }}
      shell: bash
      run: docker compose up --abort-on-container-exit --quiet-pull
      env:
        GITHUB_ACTOR: ${{ github.actor }}
        GITHUB_TOKEN: ${{ inputs.access-token }}

  

