version: "3.8"
services:
  serializationerrorcatch-test:
    build:
      context: ComponentTest
      secrets:
        - GITHUB_TOKEN
        - GITHUB_ACTOR
    environment:
      Kafka__Url: kafka:19092
      Kafka__SecurityProtocol: SaslPlaintext
      Kafka__SaslMechanism: OAuthBearer
      Kafka__OAuth2__ClientId: default-access
      Kafka__OAuth2__ClientSecret: default-access-secret
      Kafka__OAuth2__TokenEndpoint: http://keycloak:1852/realms/local-development/protocol/openid-connect/token
      Kafka__OAuth2__Scope: kafka
    depends_on:
      serializationerrorcatch-jobmanager:
        condition: service_healthy

  serializationerrorcatch-jobmanager:
    build:
      secrets:
        - GITHUB_TOKEN
        - GITHUB_ACTOR
    command: |
      standalone-job
      --job-classname cheetah.example.serializationerrorcatch.job.SerializationErrorCatchJob
      --kafka-bootstrap-servers kafka:19092
      --input-kafka-topic-main-source SerializationErrorCatchInputTopic
      --output-kafka-topic-main-sink SerializationErrorCatchOutputTopic
      --kafka-group-id SerializationErrorCatch-group-id
      --kafka-security-protocol SASL_PLAINTEXT
    environment:
      KAFKA_CLIENT_ID: default-access
      KAFKA_CLIENT_SECRET: default-access-secret
      KAFKA_SCOPE: kafka
      KAFKA_TOKEN_URL: http://keycloak:1852/realms/local-development/protocol/openid-connect/token
      FLINK_PROPERTIES: |
        jobmanager.rpc.address: serializationerrorcatch-jobmanager
        scheduler-mode: reactive
        rest.flamegraph.enabled: true
        state.backend.type: rocksdb
        state.checkpoints.dir: file:///checkpoints/processing
        state.savepoints.dir: file:///checkpoints/processing
        execution.checkpointing.interval: 300 seconds
        execution.checkpointing.min-pause: 240 seconds
        metrics.reporters: prom
        metrics.reporter.prom.factory.class: org.apache.flink.metrics.prometheus.PrometheusReporterFactory
    depends_on:
      - serializationerrorcatch-taskmanager
    ports:
      - "18081:8081"
    volumes:
      - flink:/checkpoints
    healthcheck:
      test: curl localhost:8081/jobs | grep -q '"status":"RUNNING"' || exit -1
      interval: 1s
      timeout: 1s
      retries: 30

  serializationerrorcatch-taskmanager:
    build:
      secrets:
        - GITHUB_TOKEN
        - GITHUB_ACTOR
    command: taskmanager
    environment:
      FLINK_PROPERTIES: |
        jobmanager.rpc.address: serializationerrorcatch-jobmanager
        taskmanager.memory.process.size: 4gb
        taskmanager.numberOfTaskSlots: 2
        metrics.reporters: prom
        metrics.reporter.prom.factory.class: org.apache.flink.metrics.prometheus.PrometheusReporterFactory
    ports:
      - "9249:9249"
    volumes:
      - flink:/checkpoints

volumes:
  flink:

secrets:
  GITHUB_TOKEN:
    environment: GITHUB_TOKEN
  GITHUB_ACTOR:
    environment: GITHUB_ACTOR

networks:
  default:
    name: "cheetah-infrastructure"
    external: true
