name: "Build and test maven project"
description: Action that builds and test maven project

inputs:
  PAT:
    description: A personal access token with permission to publish a package
    required: true
  settings-path:
    description: Path of maven settings file
    required: true

runs:
  using: composite

  steps:
  - name: Set up JDK 11
    uses: actions/setup-java@v3
    with:
      java-version: "11"
      distribution: "temurin"
      server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
      settings-path: ${{ inputs.settings-path }} # location for the settings.xml file
      cache: 'maven'

  - name: Build with Maven
    shell: bash
    working-directory: ${{ inputs.settings-path }}
    run: mvn install -B -s settings.xml
    env:
      GITHUB_TOKEN: ${{ inputs.PAT }}