---
services:
  avrotojson-test:
    build:
      context: ComponentTest
      secrets:
        - GITHUB_TOKEN
        - GITHUB_ACTOR
    environment:
      Kafka__Url: kafka:19092
      Kafka__SecurityProtocol: SaslPlaintext
      Kafka__SaslMechanism: OAuthBearer
      Kafka__OAuth2__ClientId: default-access
      Kafka__OAuth2__ClientSecret: default-access-secret
      Kafka__OAuth2__TokenEndpoint: http://keycloak:1852/realms/local-development/protocol/openid-connect/token
      Kafka__OAuth2__Scope: kafka
      SchemaRegistry__Url: schema-registry:8080/apis/ccompat/v7
      SchemaRegistry__OAuth2__ClientId: default-access
      SchemaRegistry__OAuth2__ClientSecret: default-access-secret
      SchemaRegistry__OAuth2__TokenEndpoint: http://keycloak:1852/realms/local-development/protocol/openid-connect/token
      SchemaRegistry__OAuth2__Scope: schema-registry
    depends_on:
      avrotojson-jobmanager:
        condition: service_healthy

  avrotojson-jobmanager:
    build:
      secrets:
        - GITHUB_TOKEN
        - GITHUB_ACTOR
    command: |
      standalone-job
      --job-classname cheetah.example.job.AvroToJsonJob
      --kafka-bootstrap-servers kafka:19092
      --kafka-group-id AvroToJson-group-id
      --schema-registry-url http://schema-registry:8080/apis/ccompat/v7
      --input-kafka-topic-main-source AvroToJsonInputTopic
      --output-kafka-topic-main-sink AvroToJsonOutputTopic
    environment:
      SECURITY_PROTOCOL: SASL_PLAINTEXT
      TOKEN_URL: http://keycloak:1852/realms/local-development/protocol/openid-connect/token
      KAFKA_CLIENT_ID: default-access
      KAFKA_CLIENT_SECRET: default-access-secret
      KAFKA_SCOPE: kafka
      SCHEMA_REGISTRY_CLIENT_ID: default-access
      SCHEMA_REGISTRY_CLIENT_SECRET: default-access-secret
      SCHEMA_REGISTRY_SCOPE: schema-registry
      FLINK_PROPERTIES: |
        jobmanager.rpc.address: avrotojson-jobmanager
        scheduler-mode: reactive
        rest.flamegraph.enabled: true
        state.backend.type: hashmap
        state.checkpoints.dir: file:///checkpoints/processing
        state.savepoints.dir: file:///checkpoints/processing
        execution.checkpointing.interval: 300 seconds
        execution.checkpointing.min-pause: 240 seconds
    volumes:
      - flink:/checkpoints
    healthcheck:
      test: curl localhost:8081/jobs | grep -q '"status":"RUNNING"' || exit -1
      interval: 1s
      timeout: 1s
      retries: 30
    depends_on:
      - avrotojson-taskmanager

  avrotojson-taskmanager:
    build:
      secrets:
        - GITHUB_TOKEN
        - GITHUB_ACTOR
    command: taskmanager
    environment:
      FLINK_PROPERTIES: |
        jobmanager.rpc.address: avrotojson-jobmanager
        taskmanager.memory.process.size: 4gb
        taskmanager.numberOfTaskSlots: 2
    volumes:
      - flink:/checkpoints

networks:
  default:
    name: "cheetah-infrastructure"
    external: true

volumes:
  flink:

secrets:
  GITHUB_TOKEN:
    environment: GITHUB_TOKEN
  GITHUB_ACTOR:
    environment: GITHUB_ACTOR
