services:
  # Copied from EnrichStream project
  # Start of EnrichStream project
  enrichstream-test:
    build:
      context: ComponentTest
      dockerfile: Dockerfile
      secrets:
        - GITHUB_TOKEN
        - GITHUB_ACTOR
    environment:
      KAFKA__URL: kafka:19092
      KAFKA__OAUTH2__CLIENTID: default-access
      KAFKA__OAUTH2__CLIENTSECRET: default-access-secret
      KAFKA__OAUTH2__SCOPE: kafka
      KAFKA__OAUTH2__TOKENENDPOINT: http://keycloak:1852/realms/local-development/protocol/openid-connect/token
    depends_on:
      enrichstream-jobmanager:
        condition: service_healthy

  enrichstream-jobmanager:
    image: ${DOCKER_REGISTRY-}enrichstream-job
    build:
      dockerfile: Dockerfile
      args:
        - MAVEN_ARGS=${EXTRA_MAVEN_ARGS-}
      secrets:
        - GITHUB_TOKEN
        - GITHUB_ACTOR
    command: |
      standalone-job
      --job-classname cheetah.example.enrichstream.job.EnrichStreamJob
      --kafka-bootstrap-servers kafka:19092
      --kafka-group-id EnrichStream-group-id
      --kafka-security-protocol SASL_PLAINTEXT
      --input-kafka-topic-enriching EnrichStreamEnrichTopic
      --input-kafka-topic-main EnrichStreamInputTopic
      --output-kafka-topic EnrichStreamOutputTopic
    environment:
      KAFKA_CLIENT_ID: default-access
      KAFKA_CLIENT_SECRET: default-access-secret
      KAFKA_SCOPE: kafka
      KAFKA_TOKEN_URL: http://keycloak:1852/realms/local-development/protocol/openid-connect/token
      FLINK_PROPERTIES: |
        jobmanager.rpc.address: enrichstream-jobmanager
        scheduler-mode: reactive
        rest.flamegraph.enabled: true
        state.backend: rocksdb
        state.checkpoints.dir: file:///checkpoints/processing
        state.savepoints.dir: file:///checkpoints/processing
        execution.checkpointing.interval: 300 seconds
        execution.checkpointing.min-pause: 240 seconds
    depends_on:
      - enrichstream-taskmanager
    volumes:
      - flink:/checkpoints
    healthcheck:
      test: curl localhost:8081/jobs | grep -q '"status":"RUNNING"' || exit -1
      interval: 1s
      timeout: 1s
      retries: 30

  enrichstream-taskmanager:
    image: ${DOCKER_REGISTRY-}enrichstream-job
    build:
      dockerfile: Dockerfile
      args:
        - MAVEN_ARGS=${EXTRA_MAVEN_ARGS-}
      secrets:
        - GITHUB_TOKEN
        - GITHUB_ACTOR
    command: taskmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: enrichstream-jobmanager
        taskmanager.memory.process.size: 4gb
        taskmanager.numberOfTaskSlots: 2
    volumes:
      - flink:/checkpoints
  # End of EnrichStream service

  # Start of JsonToAvro service
  jsontoavro-jobmanager:
    image: ${DOCKER_REGISTRY-}jsontoavro-job
    build:
      dockerfile: Dockerfile
      args:
        - MAVEN_ARGS=${EXTRA_MAVEN_ARGS-}
      secrets:
        - GITHUB_TOKEN
        - GITHUB_ACTOR
    command: |
      standalone-job
      --job-classname cheetah.example.job.JsonToAvroJob
      --kafka-bootstrap-servers kafka:19092
      --input-kafka-topic EnrichStreamOutputTopic
      --output-kafka-topic jsonToAvroOutputTopic
      --kafka-group-id jsonToAvro-group-id
      --kafka-security-protocol SASL_PLAINTEXT
      --sr-url http://schema-registry:8080/apis/ccompat/v7
    environment:
      KAFKA_CLIENT_ID: default-access
      KAFKA_CLIENT_SECRET: default-access-secret
      KAFKA_SCOPE: kafka
      KAFKA_TOKEN_URL: http://keycloak:1852/realms/local-development/protocol/openid-connect/token
      SCHEMA_REGISTRY_CLIENT_ID: default-access
      SCHEMA_REGISTRY_CLIENT_SECRET: default-access-secret
      SCHEMA_REGISTRY_SCOPE: schema-registry
      SCHEMA_REGISTRY_TOKEN_URL: http://keycloak:1852/realms/local-development/protocol/openid-connect/token
      FLINK_PROPERTIES: |
        jobmanager.rpc.address: jsontoavro-jobmanager
        scheduler-mode: reactive
        rest.flamegraph.enabled: true
        state.backend: rocksdb
        state.checkpoints.dir: file:///checkpoints/processing
        state.savepoints.dir: file:///checkpoints/processing
        execution.checkpointing.interval: 300 seconds
        execution.checkpointing.min-pause: 240 seconds
    depends_on:
      - jsontoavro-taskmanager
    volumes:
      - flink:/checkpoints
    healthcheck:
      test: curl localhost:8081/jobs | grep -q '"status":"RUNNING"' || exit -1
      interval: 1s
      timeout: 1s
      retries: 30

  jsontoavro-taskmanager:
    image: ${DOCKER_REGISTRY-}jsontoavro-job
    build:
      dockerfile: Dockerfile
      args:
        - MAVEN_ARGS=${EXTRA_MAVEN_ARGS-}
      secrets:
        - GITHUB_TOKEN
        - GITHUB_ACTOR
    command: taskmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jsontoavro-jobmanager
        taskmanager.memory.process.size: 4gb
        taskmanager.numberOfTaskSlots: 2
    volumes:
      - flink:/checkpoints
# End of JsonToAvro service

# Shared top level elements
volumes:
  flink:

secrets:
  GITHUB_TOKEN:
    environment: GITHUB_TOKEN
  GITHUB_ACTOR:
    environment: GITHUB_ACTOR

networks:
  default:
    name: "cheetah-infrastructure"
    external: true
