---
services:
  storage-job-jobmanager:
    image: ghcr.io/trifork/cheetah-app-jobs:release-v2.1
    ports:
      - "28087:8081"
      - "29256:9249"
    command: |
      standalone-job
      --job-classname com.trifork.cheetah.apps.jobs.storage.OpensearchStorageJob
      --kafka-bootstrap-servers kafka:19092
      --kafka-group-id storage-job-group
      --input-kafka-topic InputTopic

      --index-base-name your-index-name

      --output-es-hosts http://opensearch:9200
    environment:
      - INPUT_KAFKA_CLIENT_ID=flink
      - INPUT_KAFKA_CLIENT_SECRET=ThisIsASecret
      - INPUT_KAFKA_TOKEN_URL=http://cheetahoauthsimulator/oauth2/token
      - OPENSEARCH_CLIENT_ID=opensearch
      - OPENSEARCH_CLIENT_SECRET=ThisIsASecret
      - OPENSEARCH_TOKEN_URL=http://cheetahoauthsimulator/oauth2/token
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: storage-job-jobmanager
        scheduler-mode: reactive
        rest.flamegraph.enabled: true
        state.backend: hashmap
        state.checkpoints.dir: file:///checkpoints/storage
        state.savepoints.dir: file:///checkpoints/storage
        execution.checkpointing.interval: 20 seconds
        execution.checkpointing.min-pause: 10 seconds
        metrics.reporters: prom
        metrics.reporter.prom.factory.class: org.apache.flink.metrics.prometheus.PrometheusReporterFactory
    volumes:
      - flink:/checkpoints
    depends_on:
      - storage-job-taskmanager

  storage-job-taskmanager:
    image: ghcr.io/trifork/cheetah-app-jobs:release-v2.1
    command: taskmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: storage-job-jobmanager
        taskmanager.memory.process.size: 4gb
        taskmanager.numberOfTaskSlots: 2
      - OPENSEARCH_CLIENT_ID=opensearch
      - OPENSEARCH_CLIENT_SECRET=ThisIsASecret
      - OPENSEARCH_TOKEN_URL=http://cheetahoauthsimulator/oauth2/token
    volumes:
      - flink:/checkpoints

volumes:
  flink:

networks:
  default:
    name: "cheetah-infrastructure"
    external: true
