---
services:
  storage-job-jobmanager:
    image: ghcr.io/trifork/cheetah-app-jobs:3.2.1
    ports:
      - "28087:8081"
      - "29256:9249"
    command: |
      standalone-job
      --job-classname com.trifork.cheetah.apps.jobs.storage.OpensearchStorageJob
      --kafka-bootstrap-servers kafka:19092
      --kafka-group-id storage-job-group
      --input-kafka-topic InputTopic

      --index-base-name your-index-name

      --opensearch-hosts http://opensearch:9200
    environment:
      KAFKA_SECURITY_PROTOCOL: SASL_PLAINTEXT
      INPUT_KAFKA_CLIENT_ID: default-access
      INPUT_KAFKA_CLIENT_SECRET: default-access-secret
      KAFKA_SCOPE: kafka
      INPUT_KAFKA_TOKEN_URL: http://keycloak:1852/realms/local-development/protocol/openid-connect/token
      OPENSEARCH_SECURITY_PROTOCOL: SASL_PLAINTEXT
      OPENSEARCH_CLIENT_ID: default-access
      OPENSEARCH_CLIENT_SECRET: default-access-secret
      OPENSEARCH_SCOPE: opensearch
      OPENSEARCH_TOKEN_URL: http://keycloak:1852/realms/local-development/protocol/openid-connect/token
      FLINK_PROPERTIES: |
        jobmanager.rpc.address: storage-job-jobmanager
        scheduler-mode: reactive
        rest.flamegraph.enabled: true
        state.backend.type: hashmap
        state.checkpoints.dir: file:///checkpoints/storage
        state.savepoints.dir: file:///checkpoints/storage
        execution.checkpointing.interval: 20 seconds
        execution.checkpointing.min-pause: 10 seconds
        metrics.reporters: prom
        metrics.reporter.prom.factory.class: org.apache.flink.metrics.prometheus.PrometheusReporterFactory
    volumes:
      - flink:/checkpoints
    depends_on:
      - storage-job-taskmanager

  storage-job-taskmanager:
    image: ghcr.io/trifork/cheetah-app-jobs:3.2.1
    command: taskmanager
    environment:
      FLINK_PROPERTIES: |
        jobmanager.rpc.address: storage-job-jobmanager
        taskmanager.memory.process.size: 4gb
        taskmanager.numberOfTaskSlots: 2
    volumes:
      - flink:/checkpoints

volumes:
  flink:

networks:
  default:
    name: "cheetah-infrastructure"
    external: true
