// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.11.2
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace cheetah.example.model.avrorecord
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("avrogen", "1.11.2")]
	public partial class Record : global::Avro.Specific.ISpecificRecord
	{
		public static global::Avro.Schema _SCHEMA = global::Avro.Schema.Parse(@"{""type"":""record"",""name"":""Record"",""namespace"":""cheetah.example.model.avrorecord"",""fields"":[{""name"":""readingTimestamp"",""type"":""string""},{""name"":""acousticNoise"",""type"":""string""},{""name"":""Unit"",""type"":""string""},{""name"":""Enhed_1"",""type"":""string""},{""name"":""Enhed_2"",""type"":""string""},{""name"":""Enhed_3"",""type"":""string""},{""name"":""infocodes"",""type"":""string""},{""name"":""loggedVolume1"",""type"":""string""},{""name"":""meterSerialNumber"",""type"":""string""},{""name"":""hourCounter"",""type"":""string""},{""name"":""volume1"",""type"":""string""}]}");
		private string _readingTimestamp;
		private string _acousticNoise;
		private string _Unit;
		private string _Enhed_1;
		private string _Enhed_2;
		private string _Enhed_3;
		private string _infocodes;
		private string _loggedVolume1;
		private string _meterSerialNumber;
		private string _hourCounter;
		private string _volume1;
		public virtual global::Avro.Schema Schema
		{
			get
			{
				return Record._SCHEMA;
			}
		}
		public string readingTimestamp
		{
			get
			{
				return this._readingTimestamp;
			}
			set
			{
				this._readingTimestamp = value;
			}
		}
		public string acousticNoise
		{
			get
			{
				return this._acousticNoise;
			}
			set
			{
				this._acousticNoise = value;
			}
		}
		public string Unit
		{
			get
			{
				return this._Unit;
			}
			set
			{
				this._Unit = value;
			}
		}
		public string Enhed_1
		{
			get
			{
				return this._Enhed_1;
			}
			set
			{
				this._Enhed_1 = value;
			}
		}
		public string Enhed_2
		{
			get
			{
				return this._Enhed_2;
			}
			set
			{
				this._Enhed_2 = value;
			}
		}
		public string Enhed_3
		{
			get
			{
				return this._Enhed_3;
			}
			set
			{
				this._Enhed_3 = value;
			}
		}
		public string infocodes
		{
			get
			{
				return this._infocodes;
			}
			set
			{
				this._infocodes = value;
			}
		}
		public string loggedVolume1
		{
			get
			{
				return this._loggedVolume1;
			}
			set
			{
				this._loggedVolume1 = value;
			}
		}
		public string meterSerialNumber
		{
			get
			{
				return this._meterSerialNumber;
			}
			set
			{
				this._meterSerialNumber = value;
			}
		}
		public string hourCounter
		{
			get
			{
				return this._hourCounter;
			}
			set
			{
				this._hourCounter = value;
			}
		}
		public string volume1
		{
			get
			{
				return this._volume1;
			}
			set
			{
				this._volume1 = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.readingTimestamp;
			case 1: return this.acousticNoise;
			case 2: return this.Unit;
			case 3: return this.Enhed_1;
			case 4: return this.Enhed_2;
			case 5: return this.Enhed_3;
			case 6: return this.infocodes;
			case 7: return this.loggedVolume1;
			case 8: return this.meterSerialNumber;
			case 9: return this.hourCounter;
			case 10: return this.volume1;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.readingTimestamp = (System.String)fieldValue; break;
			case 1: this.acousticNoise = (System.String)fieldValue; break;
			case 2: this.Unit = (System.String)fieldValue; break;
			case 3: this.Enhed_1 = (System.String)fieldValue; break;
			case 4: this.Enhed_2 = (System.String)fieldValue; break;
			case 5: this.Enhed_3 = (System.String)fieldValue; break;
			case 6: this.infocodes = (System.String)fieldValue; break;
			case 7: this.loggedVolume1 = (System.String)fieldValue; break;
			case 8: this.meterSerialNumber = (System.String)fieldValue; break;
			case 9: this.hourCounter = (System.String)fieldValue; break;
			case 10: this.volume1 = (System.String)fieldValue; break;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
