name: Run Component Test

on:
  workflow_call:
    inputs:
      folder:
        description: The folder containing the project
        required: true
        type: string
      initial-kafka-topics:
        required: false
        type: string
    secrets:
      PAT:
        description: A personal access token for retrieving private packages

jobs:
  run-component-test:
    name: Run
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check if files have changed
        uses: tj-actions/changed-files@v40
        id: changed-files
        with: 
          files: |
            ${{ inputs.folder }}/**

      - name: Build Flink States example image and run component test
        uses: ./.github/actions/component-test
        if: ${{ steps.changed-files.outputs.any_changed == 'true' }}
        with:
          context-path: ./${{ inputs.folder }}/
          access-token: ${{ secrets.PAT }}
          initial-kafka-topics: ${{ inputs.initial-kafka-topics }}