name: Component tests of all examples in Cheetah Platform Examples 
on:
  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
    types:
      - labeled
      - opened
      - edited
      - ready_for_review
      - auto_merge_enabled
      - synchronize
      - reopened
  schedule:
    - cron: '30 0 * * *'

env:
  IMAGE_REGISTRY: ghcr.io
  JAR_NAME_PATTERN: cheetah-*.jar # entrypoint assembly name
  FLINK_IMAGE_VERSION: 1.16.1

jobs:
  should-run: # seperate step to support ci/cd status checks
    runs-on: ubuntu-latest
    outputs:
      tag-check: ${{ steps.tag-check.outputs.value }}
      event-name-check: ${{ steps.event-name-check.outputs.value }}

    steps:
      # the pull request contains the 'e2e-test' label
      - name: Tag check
        id: tag-check
        if: ${{ contains(github.event.pull_request.labels.*.name, 'e2e-test') && !contains(github.event.pull_request.labels.*.name, 'blocked') }}
        run: echo "value=true" >> "$GITHUB_OUTPUT"

      # not started from a pull-request
      - name: Check for specific label
        id: event-name-check
        if: ${{github.event_name != 'pull_request'}}
        run: echo "value=true" >> "$GITHUB_OUTPUT"

  flink-state-componenttest:
    name: "Flink States example componenttests"
    needs: should-run
    runs-on: ubuntu-latest
    if: ${{ needs.should-run.outputs.event-name-check == 'true' || needs.should-run.outputs.tag-check == 'true' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Flink States example image and run component test
        uses: ./.github/actions/component-test
        with:
          context-path: ./FlinkStates/
          PAT: ${{ secrets.PACKAGE_PAT }}
          flink-image-version: ${{ env.FLINK_IMAGE_VERSION }}
          image-name: ${{ github.repository }}/FlinkState
          image-registry: ${{ env.IMAGE_REGISTRY }}
          jar-name-pattern: ${{ env.JAR_NAME_PATTERN }}

  merge-two-streams-componenttest:
    name: "Merge Two Streams example componenttest"
    needs: should-run
    runs-on: ubuntu-latest
    if: ${{ needs.should-run.outputs.event-name-check == 'true' || needs.should-run.outputs.tag-check == 'true' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Merge Two Streams example image and run component test
        uses: ./.github/actions/component-test
        with:
          context-path: ./MergeTwoStreams/
          PAT: ${{ secrets.PACKAGE_PAT }}
          flink-image-version: ${{ env.FLINK_IMAGE_VERSION }}
          image-name: ${{ github.repository }}/MergeTwoStreams
          image-registry: ${{ env.IMAGE_REGISTRY }}
          jar-name-pattern: ${{ env.JAR_NAME_PATTERN }}
          INITIAL_KAFKA_TOPICS: "MergeTwoStreamsInputTopicA MergeTwoStreamsInputTopicB"

  multiple-sideoutput-componenttest:
    name: "Multiple Side Output componenttest"
    needs: should-run
    runs-on: ubuntu-latest
    if: ${{ needs.should-run.outputs.event-name-check == 'true' || needs.should-run.outputs.tag-check == 'true' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Multiple Side Output example image and run component test
        uses: ./.github/actions/component-test
        with:
          context-path: ./MultipleSideOutput/
          PAT: ${{ secrets.PACKAGE_PAT }}
          flink-image-version: ${{ env.FLINK_IMAGE_VERSION }}
          image-name: ${{ github.repository }}/MultipleSideOutput
          image-registry: ${{ env.IMAGE_REGISTRY }}
          jar-name-pattern: ${{ env.JAR_NAME_PATTERN }}
          INITIAL_KAFKA_TOPICS: "MultipleSideOutputExampleInputTopic"

  opservability-componenttest:
    name: "Observability componenttest"
    needs: should-run
    runs-on: ubuntu-latest
    if: ${{ needs.should-run.outputs.event-name-check == 'true' || needs.should-run.outputs.tag-check == 'true' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Observability example image and run component test
        uses: ./.github/actions/component-test
        with:
          context-path: ./Observability/
          PAT: ${{ secrets.PACKAGE_PAT }}
          flink-image-version: ${{ env.FLINK_IMAGE_VERSION }}
          image-name: ${{ github.repository }}/Observability
          image-registry: ${{ env.IMAGE_REGISTRY }}
          jar-name-pattern: ${{ env.JAR_NAME_PATTERN }}
          INITIAL_KAFKA_TOPICS: "ObservabilityInputTopic"
  
  tumblingwindow-componenttest:
    name: "Tumbling Window componenttest"
    needs: should-run
    runs-on: ubuntu-latest
    if: ${{ needs.should-run.outputs.event-name-check == 'true' || needs.should-run.outputs.tag-check == 'true' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Tumbling Window example image and run component test
        uses: ./.github/actions/component-test
        with:
          context-path: ./TumblingWindow/
          PAT: ${{ secrets.PACKAGE_PAT }}
          flink-image-version: ${{ env.FLINK_IMAGE_VERSION }}
          image-name: ${{ github.repository }}/TumblingWindow
          image-registry: ${{ env.IMAGE_REGISTRY }}
          jar-name-pattern: ${{ env.JAR_NAME_PATTERN }}
          INITIAL_KAFKA_TOPICS: "TumblingWindowInputTopic"

