name: Component tests of all examples in Cheetah Platform Examples 
on:
  workflow_dispatch:
  
  push:
    branches: ["main"]

  pull_request:
    branches: ["main"]

  schedule:
  # * is a special character in YAML so you have to quote this string
  - cron: '30 0 * * *'

jobs:
  flink-state-component-test:
    name: "Flink States example component test"
    runs-on: ubuntu-latest
    steps:
      - name: Build Flink States example image and run component test
        uses: ./.github/actions/component-test
        with:
          context-path: ./FlinkStates/
          access-token: ${{ secrets.PACKAGE_PAT }}
          initial-kafka-topics: "MergeTwoStreamsInputTopicA MergeTwoStreamsInputTopicB"

  merge-two-streams-component-test:
    name: "Merge Two Streams example component test"
    runs-on: ubuntu-latest
    steps:
      - name: Build Merge Two Streams example image and run component test
        uses: ./.github/actions/component-test
        with:
          context-path: ./MergeTwoStreams/
          access-token: ${{ secrets.PACKAGE_PAT }}
          initial-kafka-topics: "MergeTwoStreamsInputTopicA MergeTwoStreamsInputTopicB"

  multiple-sideoutput-component-test:
    name: "Multiple Side Output component test"
    runs-on: ubuntu-latest
    steps:
      - name: Build Multiple Side Output example image and run component test
        uses: ./.github/actions/component-test
        with:
          context-path: ./MultipleSideOutput/
          access-token: ${{ secrets.PACKAGE_PAT }}
          initial-kafka-topics: "MultipleSideOutputExampleInputTopic"

  observability-component-test:
    name: "Observability component test"
    runs-on: ubuntu-latest
    steps:
      - name: Build Observability example image and run component test
        uses: ./.github/actions/component-test
        with:
          context-path: ./Observability/
          access-token: ${{ secrets.PACKAGE_PAT }}
          initial-kafka-topics: "ObservabilityInputTopic"
  
  tumbling-window-component-test:
    name: "Tumbling Window component test"
    runs-on: ubuntu-latest
    steps:
      - name: Build Tumbling Window example image and run component test
        uses: ./.github/actions/component-test
        with:
          context-path: ./TumblingWindow/
          access-token: ${{ secrets.PACKAGE_PAT }}
          initial-kafka-topics: "TumblingWindowInputTopic"

  external-lookup-component-test:
    name: "Tumbling Window component test"
    runs-on: ubuntu-latest
    steps:
      - name: Build Tumbling Window example image and run component test
        uses: ./.github/actions/component-test
        with:
          context-path: ./ExternalLookup/
          access-token: ${{ secrets.PACKAGE_PAT }}
          initial-kafka-topics: "ExternalLookupInputTopic"

