name: Component tests of all examples in Cheetah Platform Examples 
on:
  workflow_dispatch:
  
  push:
    branches: ["main"]

  pull_request:
    branches: ["main"]
    types:
      - labeled
      - opened
      - edited
      - ready_for_review
      - auto_merge_enabled
      - synchronize
      - reopened
      
  schedule:
  # * is a special character in YAML so you have to quote this string
  - cron: '30 0 * * *'

jobs:
  should-run: # seperate step to support ci/cd status checks
    uses: trifork/cheetah-infrastructure-utils-workflows/.github/workflows/e2e-should-run.yml@main

  flink-state-component-test:
    name: "Flink States example component test"
    needs: should-run
    runs-on: ubuntu-latest
    if: ${{ needs.should-run.outputs.should-run }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Flink States - Check if files has changed
        uses: tj-actions/changed-files@v40
        id: changed-files
        with: 
          files: |
            FlinkStates/ComponentTest/**
            FlinkStates/src/**
            FlinkStates/.ignore
            FlinkStates/*.yaml
            FlinkStates/Dockerfile
            FlinkStates/*.xml

      - name: Build Flink States example image and run component test
        uses: ./.github/actions/component-test
        if: ${{ steps.changed-files.outputs.any_changed == 'true' }}
        with:
          context-path: ./FlinkStates/
          access-token: ${{ secrets.PACKAGE_PAT }}
          initial-kafka-topics: "MergeTwoStreamsInputTopicA MergeTwoStreamsInputTopicB"

  merge-two-streams-component-test:
    name: "Merge Two Streams example component test"
    needs: should-run
    if: ${{ needs.should-run.outputs.should-run }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Merge Two Streams - Check if files has changed
        uses: tj-actions/changed-files@v40
        id: changed-files
        with: 
          files: |
            MergeTwoStreams/ComponentTest/**
            MergeTwoStreams/src/**
            MergeTwoStreams/.ignore
            MergeTwoStreams/*.yaml
            MergeTwoStreams/Dockerfile
            MergeTwoStreams/*.xml

      - name: Build Merge Two Streams example image and run component test
        uses: ./.github/actions/component-test
        if: ${{ steps.changed-files.outputs.any_changed == 'true' }}
        with:
          context-path: ./MergeTwoStreams/
          access-token: ${{ secrets.PACKAGE_PAT }}
          initial-kafka-topics: "MergeTwoStreamsInputTopicA MergeTwoStreamsInputTopicB"

  multiple-sideoutput-component-test:
    name: "Multiple Side Output component test"
    needs: should-run
    if: ${{ needs.should-run.outputs.should-run }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Multiple Side Output - Check if files has changed
        uses: tj-actions/changed-files@v40
        id: changed-files
        with: 
          files: |
            MultipleSideOutput/ComponentTest/**
            MultipleSideOutput/src/**
            MultipleSideOutput/.ignore
            MultipleSideOutput/*.yaml
            MultipleSideOutput/Dockerfile
            MultipleSideOutput/*.xml

      - name: Build Multiple Side Output example image and run component test
        uses: ./.github/actions/component-test
        if: ${{ steps.changed-files.outputs.any_changed == 'true' }}
        with:
          context-path: ./MultipleSideOutput/
          access-token: ${{ secrets.PACKAGE_PAT }}
          initial-kafka-topics: "MultipleSideOutputExampleInputTopic"

  observability-component-test:
    name: "Observability component test"
    needs: should-run
    if: ${{ needs.should-run.outputs.should-run }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Observability - Check if files has changed
        uses: tj-actions/changed-files@v40
        id: changed-files
        with: 
          files: |
            Observability/ComponentTest/**
            Observability/src/**
            Observability/.ignore
            Observability/*.yaml
            Observability/Dockerfile
            Observability/*.xml

      - name: Build Observability example image and run component test
        uses: ./.github/actions/component-test
        if: ${{ steps.changed-files.outputs.any_changed == 'true' }}
        with:
          context-path: ./Observability/
          access-token: ${{ secrets.PACKAGE_PAT }}
          initial-kafka-topics: "ObservabilityInputTopic"
  
  tumbling-window-component-test:
    name: "Tumbling Window component test"
    needs: should-run
    if: ${{ needs.should-run.outputs.should-run }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Tumbling Window - Check if files has changed
        uses: tj-actions/changed-files@v40
        id: changed-files
        with: 
          files: |
            TumblingWindow/ComponentTest/**
            TumblingWindow/src/**
            TumblingWindow/.ignore
            TumblingWindow/*.yaml
            TumblingWindow/Dockerfile
            TumblingWindow/*.xml

      - name: Build Tumbling Window example image and run component test
        uses: ./.github/actions/component-test
        if: ${{ steps.changed-files.outputs.any_changed == 'true' }}
        with:
          context-path: ./TumblingWindow/
          access-token: ${{ secrets.PACKAGE_PAT }}
          initial-kafka-topics: "TumblingWindowInputTopic"

  external-lookup-component-test:
    name: "External Lookup component test"
    needs: should-run
    runs-on: ubuntu-latest
    if: ${{ needs.should-run.outputs.should-run }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: External Lookup - Check if files has changed
        uses: tj-actions/changed-files@v40
        id: changed-files
        with: 
          files: |
            ExternalLookup/ComponentTest/**
            ExternalLookup/src/**
            ExternalLookup/.ignore
            ExternalLookup/*.yaml
            ExternalLookup/Dockerfile
            ExternalLookup/*.xml

      - name: Build External Lookup example image and run component test
        uses: ./.github/actions/component-test
        if: ${{ steps.changed-files.outputs.any_changed == 'true' }}
        with:
          context-path: ./ExternalLookup/
          access-token: ${{ secrets.PACKAGE_PAT }}
          initial-kafka-topics: "ExternalLookupInputTopic"

