name: Build and test all projects in Cheetah Platform Examples with Maven
on:
  workflow_dispatch:

  push:
    branches: ["main"]
  
  pull_request:
    branches: ["main"]

  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: '30 0 * * *'

jobs:
  flink-states-build-and-test:
    name: "Flink States - Build and Test"
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Flink States - Build and Test
        uses: ./.github/actions/maven-build-and-test
        with: 
          settings-path: ./FlinkStates/
          access-token: ${{ secrets.PACKAGE_PAT }}
  
  merge-two-streams-build-and-test:
    name: "Merge Two Streams - Build and Test"
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Merge Two Streams - Build and Test
        uses: ./.github/actions/maven-build-and-test
        with: 
          settings-path: ./MergeTwoStreams/
          access-token: ${{ secrets.PACKAGE_PAT }}

  multiple-side-output-build-and-test:
    name: "Multiple Side Output - Build and Test"
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Multiple Side Output - Build and Test
        uses: ./.github/actions/maven-build-and-test
        with: 
          settings-path: ./MultipleSideOutput/
          access-token: ${{ secrets.PACKAGE_PAT }}
  
  observability-build-and-test:
    name: "Observability - Build and Test"
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Observability - Build and Test
        uses: ./.github/actions/maven-build-and-test
        with: 
          settings-path: ./Observability/
          access-token: ${{ secrets.PACKAGE_PAT }}
  
  tumbling-window-build-and-test:
    name: "Tumbling Window - Build and Test"
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Tumbling Window - Build and Test
        uses: ./.github/actions/maven-build-and-test
        with: 
          settings-path: ./TumblingWindow/
          access-token: ${{ secrets.PACKAGE_PAT }}
  
  external-lookup-build-and-test:
    name: "External Lookup - Build and Test"
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: External Lookup - Build and Test
        uses: ./.github/actions/maven-build-and-test
        with: 
          settings-path: ./ExternalLookup/
          access-token: ${{ secrets.PACKAGE_PAT }}
  
  transform-and-store-build-and-test:
    name: "Transform And Store - Build and Test"
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Transform And Store - Build and Test
        uses: ./.github/actions/maven-build-and-test
        with: 
          settings-path: ./TransformAndStore/
          access-token: ${{ secrets.PACKAGE_PAT }}