name: Run Component Tests

on:
  workflow_call:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *"
  push:
    branches: [ 'main', 'release/v**' ]
  pull_request:
    branches: [ 'main', 'release/v**' ]
    types: [ opened, synchronize, reopened, labeled ]

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  should-run:
    uses: trifork/cheetah-infrastructure-utils-workflows/.github/workflows/e2e-should-run.yml@main

  run-component-tests:
    name: Component Tests
    needs: should-run
    if: ${{ needs.should-run.outputs.should-run }}

    strategy:
      matrix:
        include:
          - folder: EnrichStream
            initial-kafka-topics: "EnrichStreamEnrichTopic EnrichStreamInputTopic EnrichStreamOutputTopic"
            
          - folder: ExternalLookup
            initial-kafka-topics: "ExternalLookupInputTopic ExternalLookupOutputTopic"
            
          - folder: FlinkStates
            initial-kafka-topics: "FlinkStatesInputTopic FlinkStatesOutputTopic-value FlinkStatesOutputTopic-reducing FlinkStatesOutputTopic-aggregating FlinkStatesOutputTopic-list FlinkStatesOutputTopic-map"
            
          - folder: MultipleSideOutput
            initial-kafka-topics: "MultipleSideOutputExampleInputTopic OutputA-events OutputB-events OutputCD-events"
            
          - folder: Observability
            initial-kafka-topics: "ObservabilityInputTopic"
            
          - folder: SerializationErrorCatch
            initial-kafka-topics: "SerializationErrorCatchInputTopic SerializationErrorCatchInputTopic SerializationErrorCatchOutputTopic"
            
          - folder: TransformAndStore
            initial-kafka-topics: "TransformAndStoreInputTopic"
            
          - folder: TumblingWindow
            initial-kafka-topics: "TumblingWindowInputTopic TumblingWindowOutputTopic"

    uses: ./.github/workflows/component-test.yml
    with:
      folder: ${{ matrix.folder }}
      initial-kafka-topics: ${{ matrix.initial-kafka-topics }}