name: Run Component Tests

on:
  workflow_call:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *"
  push:
    branches: [ 'main', 'release/v**' ]
  pull_request:
    branches: [ 'main', 'release/v**' ]
    types: [ opened, synchronize, reopened, labeled ]

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  should-run:
    uses: trifork/cheetah-infrastructure-utils-workflows/.github/workflows/e2e-should-run.yml@main

  enrich-stream-component-test:
    name: Enrich Stream
    needs: should-run
    if: ${{ needs.should-run.outputs.should-run }}
    
    uses: ./.github/workflows/component-test.yml
    with:
      folder: EnrichStream
    secrets:
      PAT: ${{ secrets.PACKAGE_PAT }}

  external-lookup-component-test:
    name: External Lookup
    needs: should-run
    if: ${{ needs.should-run.outputs.should-run }}
    
    uses: ./.github/workflows/component-test.yml
    with:
      folder: ExternalLookup
    secrets:
      PAT: ${{ secrets.PACKAGE_PAT }}

  flink-states-component-test:
    name: Flink States
    needs: should-run
    if: ${{ needs.should-run.outputs.should-run }}
    
    uses: ./.github/workflows/component-test.yml
    with:
      folder: FlinkStates
    secrets:
      PAT: ${{ secrets.PACKAGE_PAT }}

  multiple-side-outputs-component-test:
    name: Multiple Side Outputs
    needs: should-run
    if: ${{ needs.should-run.outputs.should-run }}
    
    uses: ./.github/workflows/component-test.yml
    with:
      folder: MultipleSideOutput
    secrets:
      PAT: ${{ secrets.PACKAGE_PAT }}

  observability-outputs-component-test:
    name: Observability
    needs: should-run
    if: ${{ needs.should-run.outputs.should-run }}
    
    uses: ./.github/workflows/component-test.yml
    with:
      folder: Observability
    secrets:
      PAT: ${{ secrets.PACKAGE_PAT }}

  serialization-error-catch-component-test:
    name: Serialization Error Catch
    needs: should-run
    if: ${{ needs.should-run.outputs.should-run }}
    
    uses: ./.github/workflows/component-test.yml
    with:
      folder: SerializationErrorCatch
    secrets:
      PAT: ${{ secrets.PACKAGE_PAT }}

  transform-and-store-component-test:
    name: Transform and Store
    needs: should-run
    if: ${{ needs.should-run.outputs.should-run }}
    
    uses: ./.github/workflows/component-test.yml
    with:
      folder: TransformAndStore
    secrets:
      PAT: ${{ secrets.PACKAGE_PAT }}

  tumbling-window-component-test:
    name: Tumbling Window
    needs: should-run
    if: ${{ needs.should-run.outputs.should-run }}
    
    uses: ./.github/workflows/component-test.yml
    with:
      folder: TumblingWindow
    secrets:
      PAT: ${{ secrets.PACKAGE_PAT }}